config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    root                                'home#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    resources :products, only: [:show]
    resources :categories, only: [:show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  NEW_PRODUCTS_PERIOD = 1.month.ago..Time.zone.now
  scope :with_price_images, -> { includes(master: [:default_price, :images]) }
  scope :take_random, ->(n) { where(id: ids.sample(n)) }
  scope :related_products, ->(product) {
    joins(:taxons).
      where(spree_taxons: { id: product.taxon_ids, taxonomy_id: Spree::Taxonomy.find_categories! }).
      with_price_images.
      where.not(id: product.id).
      distinct
  }
  scope :new_products, -> {
    where(available_on: NEW_PRODUCTS_PERIOD).
      with_price_images.
      order(available_on: :desc)
  }
end

app/models/spree/taxonomy_decorator.rb
Spree::Taxonomy.class_eval do
  def self.find_categories!
    find_by!(name: 'Categories')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  def show
    @taxon = Spree::Taxon.find(params[:id])
    @products = Spree::Product.with_price_images.in_taxon(@taxon)
    @taxonomies = Spree::Taxonomy.includes(root: :children)
  end
end

app/controllers/potepan/home_controller.rb
class Potepan::HomeController < ApplicationController
  MAX_FEATURED_PRODUCTS_COUNT = 8
  def index
    @featured_products = Spree::Product.new_products.first(MAX_FEATURED_PRODUCTS_COUNT)
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  MAX_RELATED_PRODUCTS_COUNT = 4
  def show
    @product = Spree::Product.find(params[:id])
    @related_products = Spree::Product.related_products(@product).take_random(MAX_RELATED_PRODUCTS_COUNT)
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  layout "sample"
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title:)
    base_title = "BIGBAG Store"
    return base_title if page_title.empty?
    page_title + " | " + base_title
  end
end

app/views/layouts/_head.html.erb
<%= csrf_meta_tags %>
<!-- GOOGLE FONT -->
<%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', media: "all" %>

app/views/layouts/_header.html.erb
<!-- HEADER -->
<div class="header clearfix">
  <!-- TOPBAR -->
  <div class="topBar">
    <div class="container">
      <div class="row">
        <div class="col-md-6 hidden-sm hidden-xs">
          <ul class="list-inline">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
            <li><a href="#"><i class="fa fa-vimeo"></i></a></li>
            <li><a href="#"><i class="fa fa-tumblr"></i></a></li>
          </ul>
        </div>
        <div class="col-md-6 col-xs-12">
          <ul class="list-inline pull-right">
            <li><span><a data-toggle="modal" href='#login'>Log in</a><small>or</small><a data-toggle="modal" href='#signup'>Create an account</a></span></li>
            <li class="dropdown searchBox">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>
                  <span class="input-group">
                    <input type="text" class="form-control" placeholder="Search…" aria-describedby="basic-addon2">
                    <span class="input-group-addon" id="basic-addon2">Search</span>
                  </span>
                </li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-shopping-cart"></i>$0</a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>Item(s) in your cart</li>
                <li>
                  <a href="#">
                    <div class="media">
                      <%= image_tag("img/home/cart-items/cart-item-01.jpg", :class => "media-left media-object", :alt => "cart-Image") %>
                      <div class="media-body">
                        <h5 class="media-heading">INCIDIDUNT UT <br><span>2 X $199</span></h5>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <div class="media">
                      <%= image_tag("img/home/cart-items/cart-item-01.jpg", :class => "media-left media-object", :alt => "cart-Image") %>
                      <div class="media-body">
                        <h5 class="media-heading">INCIDIDUNT UT <br><span>2 X $199</span></h5>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <div class="btn-group" role="group" aria-label="...">
                    <button type="button" class="btn btn-default">Shopping Cart</button>
                    <button type="button" class="btn btn-default">Checkout</button>
                  </div>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <!-- NAVBAR -->
  <nav class="navbar navbar-main navbar-default" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag("img/logo.png", :alt => ""), potepan_root_path, class:"navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", potepan_root_path %></li>
          <li class="dropdown megaDropMenu">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</b></a>
            <ul class="dropdown-menu row">
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                 <li>レディース</li>
                 <li><a href="product_grid_left_sidebar.html">トップス</a></li>
                 <li><a href="product_grid_left_sidebar.html">アウター</a></li>
                 <li><a href="product_grid_left_sidebar.html">ボトムス</a></li>
                 <li><a href="product_grid_left_sidebar.html">靴</a></li>
                  <!-- <li><a href="product-grid-right-sidebar.html">Products Sidebar Right</a></li>
                  <li><a href="product-grid-3-col-filter.html">Products 3 Columns V1</a></li>
                  <li><a href="product-grid-3-col.html">Products 3 Columns V2</a></li>
                  <li><a href="product-grid-4-col.html">Products 4 Columns</a></li> -->
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <!-- <li>Products List View</li>
                  <li><a href="product-list-left-sidebar.html">Products Sidebar Left</a></li>
                  <li><a href="product-list-right-sidebar.html">Products Sidebar Right</a></li> -->
                  <li class="listHeading">メンズ</li>
                  <li><a href="product_grid_left_sidebar.html">トップス</a></li>
                 <li><a href="product_grid_left_sidebar.html">アウター</a></li>
                 <li><a href="product_grid_left_sidebar.html">ボトムス</a></li>
                 <li><a href="product_grid_left_sidebar.html">靴</a></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>キッズ</li>
                  <li><a href="product_grid_left_sidebar.html">トップス</a></li>
                 <li><a href="product_grid_left_sidebar.html">アウター</a></li>
                 <li><a href="product_grid_left_sidebar.html">ボトムス</a></li>
                 <li><a href="product_grid_left_sidebar.html">靴</a></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>アクセサリー</li>
                  <li><a href="product_grid_left_sidebar.html">モバイルケース・アクセサリー</a></li>
                    <li><a href="product_grid_left_sidebar.html">財布・革小物</a></li>
                     <li><a href="product_grid_left_sidebar.html">腕時計</a></li>
                      <li><a href="product_grid_left_sidebar.html">帽子</a></li>
                </ul>
              <!--   <a href="#" class="menu-photo"><img src="img/menu-photo.jpg" alt="menu-img"></a> -->
              </li>
            </ul>
          </li>
          <% if current_page?(potepan_root_path) %>
            <li class="dropdown">
              <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">About US</a>
              <ul class="dropdown-menu dropdown-menu-left">
                <li><%= link_to "About Us", potepan_about_us_path %></li>
                <!-- <li><a href="signup.html">Register</a></li>
                <li><a href="signup-login.html">Register or Login</a></li>
                <li><a href="login.html">Login</a></li> -->
                <!-- <li><a href="lost-password.html">Password Recovery</a></li> -->
                <li><%= link_to "Privacy Policy", potepan_privacy_policy_path %></li>
                <!-- <li><a href="terms-and-conditions.html">Terms &amp; Conditions</a></li> -->
                <!-- <li><a href="404.html">404 Not Found</a></li> -->
                <!-- <li><a href="coming-soon.html">Coming Soon</a></li>  -->
              </ul>
            </li>
          <% else %>
            <li class="dropdown">
              <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">pages</a>
              <ul class="dropdown-menu dropdown-menu-left">
                <li><a href="about_us.html">About Us</a></li>
                <li><a href="signup.html">Register</a></li>
                <li><a href="signup-login.html">Register or Login</a></li>
                <li><a href="login.html">Login</a></li>
                <li><a href="lost-password.html">Password Recovery</a></li>
                <li><a href="privacy_policy.html">Privacy Policy</a></li>
                <li><a href="terms-and-conditions.html">Terms &amp; Conditions</a></li>
                <li><a href="404.html">404 Not Found</a></li>
                <li><a href="coming-soon.html">Coming Soon</a></li>
              </ul>
            </li>
          <% end %>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">blog</a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li><a href="blog_right_sidebar.html">Right Sidebar</a></li>
              <li><a href="blog_left_sidebar.html">Left Sidebar</a></li>
              <li><a href="blog-fullwidth.html">Full Width</a></li>
              <li><a href="blog-single-fullwidth.html">Single Post</a></li>
              <li><a href="blog_single_right_sidebar.html">Single Right Sidebar</a></li>
              <li><a href="blog_single_left_sidebar.html">Single Left Sidebar</a></li>
            </ul>
          </li>
          <% if !current_page?(potepan_root_path) %>
            <li class="dropdown">
              <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account</a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li><a href="account-dashboard.html">Dashboard</a></li>
                <li><a href="account-profile.html">Profile</a></li>
                <li><a href="account-all-orders.html">All Orders</a></li>
                <li><a href="account-single-order.html">Single Order</a></li>
                <li><a href="account-wishlist.html">Wishlist</a></li>
                <li><a href="account-address.html">Address</a></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>
</div>

app/views/layouts/sample.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Potepanec</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/potepan/categories/show.html.erb
<% provide(:title, @taxon.name) %>
<%= render partial: 'shared/light_section_page_header', locals: { taxon: @taxon, name: @taxon.name } %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <%=render partial: 'shared/sidebar', locals: { taxonomies: @taxonomies } %>
      <div class="col-md-9 col-sm-8 col-xs-12">
        <div class="row filterArea">
          <div class="col-xs-6">
            <select name="guiest_id1" id="guiest_id1" class="select-drop">
              <option value="0">並び替え</option>
              <option value="1">人気順</option>
              <option value="2">安い順</option>
              <option value="3">新着順</option>
              <option value="3">高い順</option>
            </select>
          </div>
          <div class="col-xs-6">
            <div class="btn-group pull-right" role="group">
              <button type="button" class="btn btn-default active" onclick="window.location.href='product_grid_left_sidebar.html'"><i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
              <button type="button" class="btn btn-default" onclick="window.location.href='product_list_left_sidebar.html'"><i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
            </div>
          </div>
        </div>
        <div class="row">
          <% @products.each do |product| %>
            <div class="col-sm-4 col-xs-12">
              <div class="productBox">
                <div class="productImage clearfix">
                  <%= image_tag(product.display_image.attachment(:product), :alt => "products-img") %>
                  <div class="productMasking">
                    <ul class="list-inline btn-group" role="group">
                      <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
                      <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
                      <li><a class="btn btn-default" data-toggle="modal" href=".quick-view" ><i class="fa fa-eye"></i></a></li>
                    </ul>
                  </div>
                </div>
                <div class="productCaption clearfix">
                  <%= link_to potepan_product_path(product.id) do %>
                    <h5><%= product.name %></h5>
                  <% end %>
                  <h3><%= product.display_price %></h3>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>
<%= render 'shared/light_section_logo' %>
<%= render 'shared/product_quick_view_modal' %>

app/views/potepan/home/_featured_product.html.erb
<div class="slide">
  <div class="productImage clearfix">
    <%= image_tag(featured_product.display_image.attachment(:large), :alt => "featured-product-img") %>
    <div class="productMasking">
      <ul class="list-inline btn-group" role="group">
        <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
        <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
        <li><a data-toggle="modal" href=".quick-view" class="btn btn-default"><i class="fa fa-eye"></i></a></li>
      </ul>
    </div>
  </div>
  <div class="productCaption clearfix">
    <%= link_to potepan_product_path(featured_product.id) do %>
      <h5><%= featured_product.name %></h5>
    <% end %>
    <h3><%= featured_product.display_price %></h3>
  </div>
</div>

app/views/potepan/products/show.html.erb
<% provide(:title, @product.name) %>
<%= render partial: 'shared/light_section_page_header', locals: { product: @product, name: @product.name } %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <div class="row singleProduct">
      <div class="col-xs-12">
        <div class="media">
          <div class="media-left productSlider">
            <div id="carousel" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                <% if @product.images.any? %>
                  <% @product.images.each_with_index do |image, i| %>
                    <div class="item <%= 'active' if i == 0 %>" data-thumb="<%= i %>">
                      <%= image_tag(image.attachment.url(:large)) %>
                    </div>
                  <% end %>
                <% end %>
              </div>
            </div>
            <div class="clearfix">
              <div id="thumbcarousel" class="carousel slide" data-interval="false">
                <div class="carousel-inner">
                  <% if @product.images.any? %>
                    <% @product.images.each_with_index do |image, i| %>
                      <div data-target="#carousel" data-slide-to="<%= i %>" class="thumb"><%= image_tag(image.attachment.url(:product)) %></div>
                    <% end %>
                  <% end %>
                </div>
                <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
                  <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
                  <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
              </div>
            </div>
          </div>
          <div class="media-body">
            <ul class="list-inline">
              <% if request.referer.present? && request.referer.match?(/potepan\/categories\/\d+$/) %>
                <%= link_to :back do %>
                  <li><i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る</a></li>
                <% end %>
              <% else %>
                <%= link_to potepan_category_path(@product.taxons.first.id) do %>
                  <li><i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る</a></li>
                <% end %>
              <% end %>
              <!-- <li><a href="#"><i class="fa fa-plus" aria-hidden="true"></i>Share This</a></li> -->
            </ul>
            <h2><%= @product.name %></h2>
            <h3><%= @product.display_price %></h3>
            <p><%= @product.description %></p>
            <span class="quick-drop">
              <select name="guiest_id3" id="guiest_id3" class="select-drop">
                <option value="0">S</option>
                <option value="1">M</option>
                <option value="2">L</option>
                <option value="3">XL</option>
              </select>
            </span>
            <span class="quick-drop resizeWidth">
              <select name="guiest_id4" id="guiest_id4" class="select-drop">
              <!--   <option value="0">Qty</option> -->
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
              </select>
            </span>
            <div class="btn-area">
              <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる<i class="fa fa-angle-right" aria-hidden="true"></i></a>
            </div>
            <div class="tabArea">
              <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#details">details</a></li>
                <li><a data-toggle="tab" href="#about-art">about art</a></li>
                <li><a data-toggle="tab" href="#sizing">sizing</a></li>
                <li><a data-toggle="tab" href="#shipping">shipping</a></li>
              </ul>
              <div class="tab-content">
                <div id="details" class="tab-pane fade in active">
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                  <ul class="list-unstyled">
                    <li>Black, Crew Neck</li>
                    <li>75% Cotton, 25% Rayon</li>
                    <li>Waterbased Ink</li>
                    <li>Wash Cold, dry low</li>
                  </ul>
                </div>
                <div id="about-art" class="tab-pane fade">
                  <p>Nulla facilisi. Mauris efficitur, massa et iaculis accumsan, mauris velit ultrices purus, quis condimentum nibh dolor ut tortor. Donec egestas tortor quis mattis gravida. Ut efficitur elit vitae dignissim volutpat. </p>
                </div>
                <div id="sizing" class="tab-pane fade">
                  <p>Praesent dui felis, gravida a auctor at, facilisis commodo ipsum. Cras eu faucibus justo. Nullam varius cursus nisi, sed elementum sem sagittis at. Nulla tellus massa, vestibulum a commodo facilisis, pulvinar convallis nunc.</p>
                </div>
                <div id="shipping" class="tab-pane fade">
                  <p>Mauris lobortis augue ex, ut faucibus nisi mollis ac. Sed volutpat scelerisque ex ut ullamcorper. Cras at velit quis sapien dapibus laoreet a id odio. Sed sit amet accumsan ante, eu congue metus. Aenean eros tortor, cursus quis feugiat sed, vestibulum vel purus.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row productsContent">
      <div class="col-xs-12">
        <div class="page-header">
          <h4>関連商品</h4>
        </div>
      </div>
      <%= render partial: 'shared/related_product', collection: @related_products %>
    </div>
  </div>
</section>
<%= render 'shared/product_quick_view_modal' %>

app/views/shared/_light_section_page_header.html.erb
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <a href="index.html">Home</a>
          </li>
          <% if defined?(product) %>
            <li class="active"><%= product.name %></li>
          <% else defined?(taxon) %>
            <li>
              <a href="#">shop</a>
            </li>
            <% taxon.self_and_ancestors.each do |t| %>
              <%= content_tag :li, class: current_page?(potepan_category_path(t.id))? 'active' : nil do %>
                <%= link_to_unless_current t.name, potepan_category_path(t.id) %>
              <% end %>
            <% end %>
          <% end %>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/shared/_related_product.html.erb
<div class="col-md-3 col-sm-6 col-xs-12">
  <div class="productBox">
    <div class="productImage clearfix">
      <%= image_tag(related_product.display_image.attachment(:product), :alt => "products-img") %>
      <div class="productMasking">
        <ul class="list-inline btn-group" role="group">
          <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
          <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
          <li><a class="btn btn-default" data-toggle="modal" href=".quick-view" ><i class="fa fa-eye"></i></a></li>
        </ul>
      </div>
    </div>
    <div class="productCaption clearfix">
      <%= link_to potepan_product_path(related_product.id) do %>
        <h5><%= related_product.name %></h5>
      <% end %>
      <h3><%= related_product.display_price %></h3>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="col-md-3 col-sm-4 col-xs-12 sideBar">
  <div class="panel panel-default">
    <div class="panel-heading">商品カテゴリー</div>
    <div class="panel-body">
      <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
        <ul class="nav navbar-nav side-nav">
          <% taxonomies.each do |taxonomy| %>
            <li>
              <a href="javascript:;" data-toggle="collapse" data-target="#<%= "group" + "#{taxonomy.id}" %>"><%= taxonomy.name %><i class="fa fa-plus"></i></a>
              <ul id="<%= "group" + "#{taxonomy.id}" %>" class="collapse collapseItem">
                <% taxonomy.root.children.each do |child| %>
                  <li>
                    <%= link_to potepan_category_path(child.id) do %>
                      <i class="fa fa-caret-right" aria-hidden="true"></i> <%= child.name %> <span>(<%= Spree::Product.in_taxon(child).count %>)</span>
                    <% end %>
                  </li>
                <% end %>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="panel panel-default priceRange">
    <div class="panel-heading">値段から探す</div>
    <div class="panel-body clearfix">
      <div class="price-slider-inner">
        <span class="amount-wrapper">
          <input type="text" id="price-amount-1" readonly>
          <strong>-</strong>
          <input type="text" id="price-amount-2" readonly>
        </span>
        <div id="price-range"></div>
      </div>
      <input class="btn btn-default" type="submit" value="絞り込む">
      <!-- <span class="priceLabel">Price: <strong>12 円- 30<円/strong></span> -->
    </div>
  </div>
  <div class="panel panel-default filterNormal">
    <div class="panel-heading">色から探す</div>
    <div class="panel-body">
      <ul class="list-unstyled">
        <li><a href="#">ブラック<span>(15)</span></a></li>
        <li><a href="#">ホワイト<span>(10)</span></a></li>
        <li><a href="#">レッド<span>(7)</span></a></li>
        <li><a href="#">ブルー<span>(12)</span></a></li>
        <li><a href="#">オレンジ<span>(12)</span></a></li>
      </ul>
    </div>
  </div>
  <div class="panel panel-default filterNormal">
    <div class="panel-heading">サイズから探す</div>
    <div class="panel-body">
      <ul class="list-unstyled clearfix">
        <li><a href="#">S<span>(15)</span></a></li>
        <li><a href="#">M<span>(10)</span></a></li>
        <li><a href="#">L<span>(7)</span></a></li>
        <li><a href="#">XL<span>(12)</span></a></li>
      </ul>
    </div>
  </div>
</div>